# application.yml
---

eureka.client.serviceUrl.defaultZone: http://localhost:8010/eureka/
#eureka.client.serviceUrl.defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
